name: example page 404 test

on: [push]

jobs:
    makeUrl:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: make
              run: |
                  node createUrl.js
            - shell: bash
              run: |
                  value=`cat ./url.txt`
                  echo ::set-env name=URLS::$value
            - name: pass
              uses: jung-han/actionsss@v0.1.5
              with:
                  global-error-log-variable: "errorLogs"
                  urls: ${{ env.URLS }}
                  browsers: "ie8"
              env:
                  BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
                  BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
