name: Share data between jobs

on: [push]

jobs:
    makeUrl:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: make
              run: |
                  node createUrl.js
            - name: Archive code coverage results
              uses: actions/upload-artifact@v1
              with:
                  name: url.txt
                  # path: url
            # - name: Archive code coverage results
            # uses: actions/upload-artifact@v1
            # with:
            # name: url.txt
    passAction:
        name: pass
        needs: makeUrl
        runs-on: ubuntu-latest
        steps:
            - name: Download result
              uses: actions/download-artifact@v1
              with:
                  name: url
            - name: pass
              uses: jung-han/actionsss@v0.1.2
              with:
                  name: url
