name: Share data between jobs

on: [push]

jobs:
    makeUrl:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: make
              run: |
                  node createUrl.js
            - shell: bash
              run: |
                  value=`cat ./url.txt`
                  echo ::set-env name=INPUT_URLS::$value
            - name: pass
              uses: jung-han/actionsss@v0.1.4
              with:
                  global-error-log-variable: "errorLogs"
