name: grap runtime error

on: [push]

jobs:
    makeUrl:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: make url
              run: |
                  node createUrl.js
            - name: set url
              shell: bash
              run: |
                  value=`cat ./url.txt`
                  echo ::set-env name=URLS::$value
            - name: grap runtime error
              uses: jung-han/actionsss@v0.4.0
              with:
                  global-error-log-variable: true
                  urls: ${{ env.URLS }}
                  browserlist: "ie8, ie9, ie10, ie11, chrome, safari, edge, firefox"
              env:
                  BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
                  BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
